# generated by datamodel-codegen:
#   filename:  course_syllabus.json
#   timestamp: 2026-09-27T18:37:32+00:00

from __future__ import annotations

from typing import TypedDict


class Timing(TypedDict):
    start: str
    end: str


class TimeZone(TypedDict):
    id: str
    name: str
    standardOffset: str


class Lesson1(TypedDict):
    id: str
    institutionId: str
    sectionId: str
    captureOccurrenceId: str
    name: str
    timing: Timing
    timeZone: TimeZone
    fromSchedule: bool
    shouldStreamLive: bool
    createdAt: str
    updatedAt: str
    isFolderLesson: bool
    displayName: str
    lessonHasName: bool


class Media(TypedDict):
    id: str
    mediaType: str
    title: str
    isAvailable: bool
    isHiddenDueToCaptions: bool
    isRead: bool
    isScheduled: bool
    isProcessing: bool
    isFailed: bool
    isPreliminary: bool
    isInteractiveMedia: bool
    is360Video: bool
    thumbnailUri: str


class Lesson(TypedDict):
    lesson: Lesson1
    medias: list[Media]
    userSectionRole: str
    captureStartedAt: str
    captureEndedAt: str
    questionCount: int
    isScheduled: bool
    hasContent: bool
    hasVideo: bool
    hasVideoHiddenDueToCaptions: bool
    hasSlideDeck: bool
    isLive: bool
    isInteractiveMedia: bool
    isPast: bool
    isFuture: bool
    is360Video: bool
    startTimeUTC: str
    endTimeUTC: str


class Datum(TypedDict):
    lesson: Lesson
    type: str


class Model(TypedDict):
    status: str
    message: str
    data: list[Datum]
